version: "3.8"

services:
  postgres_db:
    image: 'postgres:14.5-alpine'
    container_name: postgres_db
    restart: always
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
    environment:
      POSTGRES_DB: rss-tracker-dev-db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
   container_name: app
   depends_on:
      - postgres_db
   build: .
   restart: on-failure
   env_file: ./.env
   ports:
    - ${SPRING_APP_LOCAL_PORT}:${SPRING_APP_DOCKER_PORT}
   environment:
     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:${POSTGRES_DOCKER_PORT}/rss-tracker-dev-db
   volumes:
    - .m2:/root/.m2
   stdin_open: true
   tty: true

volumes:
  postgres-data:
