-- DROP TABLE IF EXISTS FEED_CONFIGURATION;
--
-- CREATE TABLE FEED_CONFIGURATION (
--                            ID INT AUTO_INCREMENT  PRIMARY KEY,
--                            DOMAIN VARCHAR(250) NOT NULL,
--                            INGESTION_ENABLE BOOLEAN NOT NULL);
--
-- CREATE TABLE FEED_ENTITY (
--                                     ID INT AUTO_INCREMENT  PRIMARY KEY,
--                                     DOMAIN VARCHAR(250) NOT NULL,
--                                     INGESTION_ENABLE BOOLEAN NOT NULL);